library(tidyverse)
library(fgsea)
library(clusterProfiler)

# Swap rnk_file and gmt_file for each analysis run
rnk_file <- "Group_DEG_up_GSEA_FC.rnk" # generated by Script 7
gmt_file <- "h.all.v2024.1.Hs.symbols.gmt" # from MSigDB

rnk_data <- read.table(rnk_file, header=TRUE, sep='\t', stringsAsFactors=FALSE)
colnames(rnk_data) <- c('Gene','Rank')
ranked_genes <- setNames(rnk_data$Rank, rnk_data$Gene)

pathways <- clusterProfiler::read.gmt(gmt_file)
pathway_list <- split(pathways$gene, pathways$term)

fgsea_res <- fgsea(pathways=pathway_list, stats=ranked_genes,
    scoreType='pos', minSize=15, maxSize=500) #change to "neg" when using downregulated set


fgsea_res_table <- as.data.frame(fgsea_res)
fgsea_res_table$geneset <- sapply(fgsea_res$leadingEdge,
    function(x) paste(x, collapse=','))

fgsea_res_table$leadingEdge <- NULL
write.csv(fgsea_res_table, "Group_fgsea_res_pos.csv") #change to "neg" when using downregulated set

dotplot <- ggplot(fgsea_res_table, aes(reorder(pathway, NES), NES)) +
  geom_point(aes(size=size, color=NES, alpha=-log10(padj))) +
  scale_color_gradient(low="blue", high="red") +
  labs(x="Pathway", y="Normalized Enrichment Score (NES)") +
  coord_flip() + theme_minimal()

ggsave("Hallmark_fgsea_dotplot_pos_all.png", plot=dotplot, width=5, height=8, dpi=600, bg="white") #change to indicate direction/gene set
